"""add kit_elements table

Revision ID: 01ab03579ec1
Revises: 91b16be805b7
Create Date: 2026-04-19 14:12:39.633037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ab03579ec1'
down_revision: Union[str, Sequence[str], None] = '91b16be805b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('element_type', sa.Enum('kick_drum', 'snare_drum', 'hi_hat', 'ride_cymbal', 'crash_cymbal', 'floor_tom', 'rack_tom', 'splash', 'china', 'drum_throne', name='elementtype'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('pos_x_cm', sa.Float(), nullable=False),
    sa.Column('pos_y_cm', sa.Float(), nullable=False),
    sa.Column('pos_z_cm', sa.Float(), nullable=False),
    sa.Column('angle_deg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['kit_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kit_elements')
    # ### end Alembic commands ###
